baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'My New Hugo Site'
[params]
[params.author]
name = 'John Doe'

[menu]
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
pre = "pen-tool"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Tags"
pre = "tag"
url = "/tags/"
weight = 3

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[services]
[services.googleAnalytics]
ID = 'G-MEASUREMENT_ID'
